version: '3.8'
services:
  service:
    build: 
      context: .
      args:
        NODE_ENV: 'development'
    container_name: service
    hostname: service
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./src/:/app/src/
      - .env/:/app/.env
    restart: unless-stopped
networks:
  app-network:
    name: app-network
    driver: bridge